### ISSUE TITLE
"强制模式"复选框被错误地置顶

### ISSUE THREAD

**Issue by ChengT-cmd** [xingchuanzhen/File-Unlock#2]
文件占用解锁器 Pro

![图片](https://user-images.githubusercontent.com/64889395/134356326-ebe1ae51-c968-4572-b9a8-b401e4c2a20a.png)

**Comment by Xing-Fax** [comment]
强制解锁功能是项目完成后临时添加的一个功能，由于疏忽大意错误的将他放在了最顶层，稍后会将此问题解决并将代码提交到仓库中，感谢您提出的问题！
